# Generated by Django 5.1 on 2026-05-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('count_training', models.PositiveIntegerField(verbose_name='Количество тренировок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit_online', 'Пополнение онлайн'), ('deposit_cash', 'Пополнение наличными'), ('payment', 'Оплата тренировки'), ('refund', 'Возврат'), ('subscription_purchase', 'Покупка абонемента')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.PositiveIntegerField(verbose_name='Осталось тренировок')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='api_services.trainingsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api_services.telegramuser')),
            ],
            options={
                'verbose_name': 'Купленный абонемент',
                'verbose_name_plural': 'Купленные абонементы',
            },
        ),
    ]
