# Generated by Django 5.1 on 2026-05-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_trainingsubscription_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
