# Generated by Django 5.1 on 2026-05-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0004_gym_remove_trainingsession_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тренировки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='price',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='api_services.trainingtype'),
        ),
    ]
