# Generated by Django 5.1 on 2026-05-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_trainingtype_remove_trainingsession_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'verbose_name': 'Тип_тренировки', 'verbose_name_plural': 'Тип_тренировок'},
        ),
    ]
