# Generated by Django 5.1 on 2026-05-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0006_alter_trainingtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
    ]
