# Generated by Django 5.1 on 2026-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0007_trainer_photo_trainingsession_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='can_use_subscription',
            field=models.BooleanField(default=False, verbose_name='Можно записаться по абонементу'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронировано'), ('cancelled', 'Отменено'), ('completed', 'Посещено')], default='booked', max_length=20),
        ),
    ]
