# Generated by Django 5.1 on 2026-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0008_trainingtype_can_use_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtype',
            name='can_use_subscription',
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='supported_subscription',
            field=models.ManyToManyField(blank=True, null=True, related_name='supported_subscription', to='api_services.trainingsubscription', verbose_name='Поддерживаемые абонементы'),
        ),
    ]
