# Generated by Django 5.1 on 2026-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0009_remove_trainingtype_can_use_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('subscription', 'Абонемент'), ('balance', 'Баланс')], max_length=20, null=True),
        ),
    ]
