# Generated by Django 5.1 on 2026-05-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0010_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_services.usersubscription', verbose_name='Абонемент, использованный для записи'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit_online', 'Пополнение онлайн'), ('deposit_cash', 'Пополнение наличными'), ('payment_sub', 'Оплата тренировки абонементом'), ('payment', 'Оплата тренировки'), ('refund', 'Возврат'), ('subscription_purchase', 'Покупка абонемента')], max_length=30),
        ),
    ]
