# Generated by Django 5.1 on 2026-05-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0012_telegramadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramadmin',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
