# Generated by Django 5.1 on 2026-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0013_telegramadmin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
